import requests from "@/lib/api";
import { PostType } from "@/models/post.interface";
import Head from "next/head";
import Link from "next/link";

interface PostsProps {
  posts: PostType[];
}

export default function Posts({ posts }: PostsProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="py-12">
        <div className="container">
          <h1>Im posts page</h1>

          <div className="space-y-6">
            {posts &&
              posts.map((post) => {
                return (
                  <Link
                    key={post.id}
                    href={`/post/${post.attributes.slug}`}
                    className="block"
                  >
                    <h2>{post.attributes.title}</h2>
                    <h3>{post.attributes.description}</h3>
                  </Link>
                );
              })}
          </div>
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const postsRes = await requests.get("posts");

  return {
    props: {
      posts: postsRes.data,
    },
  };
}
